name: vit
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - einops=0.4.1
  - jupyter
  - matplotlib
  - munch=2.5.0
  - numpy=1.23.1
  - scipy
  - pandas
  - python=3.10.4
  - pytorch=1.12.1
  - torchvision
  - torchaudio
  - cudatoolkit=11.3
  - timm=0.9.2
  - torchinfo=1.7.0
  - matplotlib
  - wandb=0.13.1
  - pytorch-lightning=1.9.3
  - torchmetrics=0.9.3
  - seaborn=0.11.2
  - easydict
  - pytest
  - pip:
    - ml-collections==0.1.1
    - pandas==1.4.3
    - pillow==9.2.0
    - pip==22.1.2
